name: Deploy Next.js App to Hostinger

on:
  push:
    branches:
      - main # Trigger the workflow on push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0" # Match your project's Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the Next.js project
      - name: Build project
        run: |
          npm run build

      # Step 5: Export the project as a static site
      - name: Export project
        run: npm run export

      # Step 6: Deploy to Hostinger via FTP
      - name: Deploy to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.FTP_HOST }} # FTP host provided in GitHub secrets
          username: ${{ secrets.FTP_USERNAME }} # FTP username stored in GitHub secrets
          password: ${{ secrets.FTP_PASSWORD }} # FTP password stored in GitHub secrets
          port: ${{ secrets.FTP_PORT }} # FTP port (usually 21 for FTP or 22 for SFTP)
          protocol: ftp # Use 'ftp' for FTP or 'sftp' for SFTP
          local-dir: ./out/ # Static files exported by 'npm run export'
          server-dir: ./ # Change to your remote directory (where files should be uploaded)

      - name: Clean up old files (Optional)
        run: |
          # This step is useful if you want to clean up old files in the server directory
          # E.g., you can delete files older than a certain date or remove unnecessary files.
          # This is not mandatory and should be used based on your needs.
          echo "Clean up step goes here"
